export const data = [
    {
        src: "public1.png",
        src2: ["magma.png", "public.jpg"],
        titre: "Alerte Magma",
        details: "Jeu de société Phy-Gital basé sur Fire Tower.",
        stack: ["Unity", "Game design", "Blender", "Experimentation"],
    },
    {
        src: "GOat.png",
        src2: ["Goat2.mp4","Goat1.mp4"],
        titre: "Yokai Rush",
        details: "Projet d'équipe pour un jeu de type action.",
        stack: ["Unity", "Game design", "VFX"],
    },
    {
        src: "loop1.png",
        src2: ["loop2.png","loop3.png"],
        titre: "Loops and Laps",
        details: "Gamejam 2025 sur le théme \"loop\"",
        stack: ["Unity", "UI", "VFX"],
        link: "https://wannabeez.itch.io/loops-and-laps",
    },
    {
        src: "PromInHeaven.png",
        src2: ["PromInHeaven2.png", "PromInHeaven.mp4", "PromInHeavenInterior.mp4"],
        titre: "Promenade dans l'après",
        details: "Une visite VR de l'après et l'exploration des souvenirs d'un monde vide.",
        stack: ["Unity", "VR", "VFX", "3D", "Experimentation"],
    },
    {
        src: "horror_vr.png",
        src2: ["glauque1.mp4", "glauque2.mp4"],
        titre: "Scène Glauque",
        details: "Création de scène et effets visuels pour une ambiance VR.",
        stack: ["Unity VR", "VFX"],
    },
    {
        src: "NuitBlanche.png",
        src2: "MapRN.png",
        titre: "Nuit Blanche RN 2026",
        details: "Site web pour l'événement Nuit Blanche à Rouyn-Noranda.",
        stack: ["Web", "HTML", "CSS", "JavaScript"],
        link: "https://dgrcodes.github.io/nuitblanche_siteweb/",
    },
]